# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  one:
    docker:
       - image: bash@sha256:9f0a4aa3c9931bd5fdda51b1b2b74a0398a8eabeaf9519d807e010b9d9d41993
    steps:
      - checkout
      - run: echo "hello world"
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world1"

workflow:
  build:
    jobs:
      - one
      - two      

