defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/base:10

version: 2
jobs:
  one:
    steps:
      - checkout
      - run: echo "hello world"
  two:
    steps:
      - checkout
      - run: echo "hello world1"

workflows:
  test:
    jobs:
      - one
      - two

