version: 3.1.1
jobs:
  one:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run: 
        command: echo "hello world"
  two:
    steps:
      - checkout
      - run:
        command: echo "hello world1"

workflows:
  test:
    jobs:
      - one
      - two

