version: 2.1
jobs:
  one:
    parallelism: 2
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: 
          command: yarn run cypress record
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: echo "hello world1"

workflows:
  test:
    jobs:
      - one
      - two

