version: 2.1
jobs:
  one:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: yarn install
      - run: yarn cypress open
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: echo "hello world1"

workflows:
  test:
    jobs:
      - one
      - two