version: 2.1
jobs:
  one:
    browser: chrome
    record: true
    parallel: true
    parallelism: 2
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: 
        command: npm run cypress record
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
        command: echo "hello world1"

workflows:
  test:
    jobs:
      - one
      - two

