version: 2.1
jobs:
  one:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          command: yarn run cypress run
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: echo "hello world1"

workflows:
  test:
    jobs:
      - one
      - two