version: 2.1
orbs:
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@1.0.0
jobs:
  one:
    docker:
      - image: circleci/node:7.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn cypress open
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: echo "hello world1"

workflows:
  test:
    jobs:
      - one
      - two