version: 2.1
jobs:
  one:
    docker:
      - image: cypress/base:8
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm install
                   npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run --record --key fe2fc7a2-fff0-4309-83bf-b1bad500cfa4 --group one --parallel
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: echo "hello world1"

workflows:
  test:
    jobs:
      - one
      - two