version: 2.1
jobs:
  one:
    docker:
      - image: cypress/base:8
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm install
                   npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run --record -- --parallel --group 1st-machine --spec 'cypress/integration/authen/' --browser chrome
  two:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - run:
          command: echo "Test circleci"

workflows:
  test:
    jobs:
      - one
        parallelism: 2
        parallel: true
        group: '1st-machine'
      - two